"""
Django settings for simplenote project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k3#3#^_y=wdqd4b=f0a=92q6yok28mn&@7tt^rk_lr!p-_7*7w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'note',
    'friends',
    'groups',
    'content_pages',
    'django_select2',
    'simple_email_confirmation',
    'tagging',
    'autocomplete_tags',
    'awesome_avatar',
    'ckeditor',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'privateviews.middleware.LoginRequiredMiddleware',
)

ROOT_URLCONF = 'simplenote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates', 'templatetags'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = (
    BASE_DIR + '/templates/',
)


WSGI_APPLICATION = 'simplenote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django_test',
        'USER': 'postgres',
        'PASSWORD' : 'password',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

ACCOUNT_ACTIVATION_DAYS = 2
AUTH_USER_EMAIL_UNIQUE = True
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'seregasivyi@gmail.com'
EMAIL_HOST_PASSWORD = 'serg199425'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'seregasivyi@gmail.com'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    '/styles/',
    '/fonts/',
)
STATIC_DOC_ROOT = 'media/'
MEDIA_ROOT = 'media/'
MEDIA_URL = '/media/'
SITE_ID = 2

REDACTOR_OPTIONS = {'lang': 'en'}
REDACTOR_UPLOAD = 'uploads/'

PUBLIC_VIEWS = [
    'django.contrib.auth.views.password_reset_done',
    'django.contrib.auth.views.password_reset',
    'django.contrib.auth.views.password_reset_confirm',
    'django.contrib.auth.views.password_reset_complete',
]

PUBLIC_PATHS = [
    '^/login/$',
    '^/register/$',
    '^/register/complete/$',
    '^/account/confirm/(?P<confirmation_key>[a-zA-Z0-9]+)$',
    '^/confirmation_key_incorrect/$',
    '^/already_confirmed/$',
    '^/successfully_confirmed/$',
]

LOGIN_URL = '/login/'
REDACTOR_UPLOAD_HANDLER = 'redactor.handlers.DateDirectoryUploader'

AUTH_USER_MODEL = 'account.User'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = '1025'
# EMAIL_USE_TLS = False

TAGGING_AUTOCOMPLETE_JS_BASE_URL = 'static/jquery-tag-it'
CKEDITOR_UPLOAD_PATH = "uploads/"